version: '3.8'

services:
  line-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: line-server
    environment:
      FILE_PATH: "data/sample_100.txt"
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    working_dir: /app
    command: "./server"
