name: Go Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Install golangci-lint
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.1

      # Run golangci-lint
      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run ./... --output.text.colors --timeout=5m

      # Run gofmt
      - name: Run gofmt
        run: gofmt -w .

      # Run goimports
      - name: Run goimports
        run: goimports -w .
